server:
  port: 8080
  shutdown: graceful
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airport_db
    username: admin
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
management:
  endpoints:
    web:
      exposure:
        include: 'info,health,metrics'
flight:
  passenger:
    limit: 150
